using AITestAnalyzer.Models;

namespace AITestAnalyzer.Services
{
    public interface IAIAnalyzer
    {

        /// <summary>
        /// Generates cross-section integration test cases for all integration flows
        /// identified in the architecture plan. Receives all previously generated
        /// section tests to avoid duplication.
        /// </summary>
        /// <param name="requirementsMarkdown">
        /// The full requirements document in Markdown format.
        /// </param>
        /// <param name="flows">
        /// The integration flows from the approved <see cref="ArchitecturePlan"/>.
        /// </param>
        /// <param name="allSectionTests">
        /// All test cases already generated by <see cref="GenerateTestCasesForSectionAsync"/>
        /// across all sections. Passed to the AI to prevent duplicate scenarios.
        /// </param>
        /// <param name="cancellationToken">Token to cancel the operation.</param>
        /// <returns>
        /// A tuple of the generated integration test cases and the total tokens consumed.
        /// </returns>
        Task<(List<GeneratedTestCase> TestCases, int TokensUsed)> GenerateIntegrationTestsAsync(string requirementsMarkdown, List<IntegrationFlow> flows, List<GeneratedTestCase> allSectionTests, CancellationToken cancellationToken = default);

        /// <summary>
        /// Analyses the full requirements document and produces an architecture plan
        /// identifying all sections, sub-topics, recommended test counts, and
        /// cross-section integration flows.
        /// </summary>
        /// <param name="requirementsMarkdown">
        /// The full requirements document in Markdown format.
        /// </param>
        /// <param name="cancellationToken">Token to cancel the operation.</param>
        /// <returns>
        /// An <see cref="ArchitecturePlan"/> containing all sections with
        /// recommended test breakdowns and integration flows.
        /// </returns>
        Task<ArchitecturePlan> AnalyzeDocumentStructureAsync( string requirementsMarkdown, CancellationToken cancellationToken = default);

        /// <summary>
        /// Generates test cases for a single requirements section to achieve
        /// 100% coverage of all functional requirements, business rules,
        /// validation rules, and error handling paths in that section.
        /// </summary>
        /// <param name="plan">
        /// The section test plan produced by <see cref="AnalyzeDocumentStructureAsync"/>,
        /// providing section name, prefix, and sub-topics.
        /// </param>
        /// <param name="requirementsMarkdown">
        /// The full requirements document in Markdown format. The AI extracts
        /// the relevant section text internally.
        /// </param>
        /// <param name="cancellationToken">Token to cancel the operation.</param>
        /// <returns>
        /// A tuple of the generated test cases and the total tokens consumed.
        /// </returns>
        Task<(List<GeneratedTestCase> TestCases, int TokensUsed)> GenerateTestCasesForSectionAsync( SectionTestPlan plan, string requirementsMarkdown, CancellationToken cancellationToken = default);

        /// <summary>
        /// QA MODE: Analyzes a single test case for quality without requirements.
        /// Evaluates clarity, completeness, and testability.
        /// Uses gpt-4o-mini and inline system prompt in AIAnalyzer.
        /// </summary>
        /// <param name="testCase">Test case to analyze. Uses Feature, Scenario, Steps, ExpectedResult fields.</param>
        /// <returns>
        /// Tuple containing:
        /// - quality: "GOOD" or a specific, actionable issue description
        /// - tokens: total tokens consumed by this API call (0 if cached)
        /// </returns>
        Task<(string quality, int tokens)> AnalyzeTestQualityAsync(TestCase testCase);

        /// <summary>
        /// BA MODE: Analyzes test coverage against a list of extracted requirements.
        /// Identifies which requirements are covered, partially covered, or missing.
        /// Uses gpt-4o-mini and inline system prompt in AIAnalyzer.
        /// </summary>
        /// <param name="testCase">Test case to analyze against requirements.</param>
        /// <param name="requirements">Full list of extracted requirements to validate against.</param>
        /// <returns>
        /// Tuple containing:
        /// - reqFeedback: structured feedback listing missing/incomplete coverage per requirement
        /// - coverageIds: list of requirement IDs this test case touches
        /// - tokens: total tokens consumed by this API call (0 if cached)
        /// </returns>
        Task<(string reqFeedback, List<string> coverageIds, int tokens)> AnalyzeCoverageAndFeedbackAsync(
            TestCase testCase,
            List<ExtractedRequirement> requirements);

        /// <summary>
        /// GEN MODE — GENERATE PASS: Generates test cases from a requirements markdown document.
        /// Uses gpt-4.1-mini and GenSystemMessage/GenUserTemplate from PromptConfig.
        /// Output is parsed from pipe-delimited format:
        /// TC-GEN-001|Feature|Scenario|Priority|Steps|ExpectedResult
        /// </summary>
        /// <param name="requirementsMarkdown">Full requirements document in markdown or plain text format.</param>
        /// <param name="targetCount">Number of test cases to generate. Passed into GenUserTemplate as {targetCount}.</param>
        /// <returns>
        /// Tuple containing:
        /// - TestCases: list of generated test cases with PassNumber=1
        /// - Tokens: total tokens consumed by this API call
        /// Returns empty list if API call fails after retries.
        /// </returns>
        Task<(List<GeneratedTestCase> TestCases, int Tokens)> GenerateTestCasesAsync(
            string requirementsMarkdown,
            int targetCount);

        /// <summary>
        /// GEN MODE — CRITIQUE PASS: Reviews generated test cases against original requirements.
        /// Returns one CritiqueResult per test case with action KEEP, REVISE, or DROP.
        /// Uses gpt-4.1-mini and CritiqueSystemMessage/CritiqueUserTemplate from PromptConfig.
        /// Output is parsed from pipe-delimited format:
        /// TC-GEN-001|KEEP|No issues
        /// </summary>
        /// <param name="testCases">Generated test cases from the previous GENERATE or REFINE pass.</param>
        /// <param name="requirementsMarkdown">Original requirements used to generate the test cases.</param>
        /// <returns>
        /// Tuple containing:
        /// - Critiques: one CritiqueResult per input test case
        /// - Tokens: total tokens consumed by this API call
        /// Returns empty list if API call fails after retries.
        /// </returns>
        /// <remarks>
        /// Action values:
        /// KEEP = complete and clear, no changes needed.
        /// REVISE = valid but needs improvement — apply Reason as feedback in REFINE pass.
        /// DROP = duplicate, irrelevant, or untestable — remove in REFINE pass.
        /// </remarks>
        Task<(List<CritiqueResult> Critiques, int Tokens)> CritiqueTestCasesAsync(
            List<GeneratedTestCase> testCases,
            string requirementsMarkdown);

        /// <summary>
        /// GEN MODE — REFINE PASS: Applies critique feedback to produce an improved test case list.
        /// KEEP items returned unchanged. REVISE items improved per critique Reason.
        /// DROP items removed from output entirely.
        /// Uses gpt-4.1-mini and RefineSystemMessage/RefineUserTemplate from PromptConfig.
        /// </summary>
        /// <param name="testCases">Test cases from the previous GENERATE or REFINE pass.</param>
        /// <param name="critiques">Critique results from the most recent CRITIQUE pass.</param>
        /// <param name="requirementsMarkdown">Original requirements — included for context in the refine prompt.</param>
        /// <returns>
        /// Tuple containing:
        /// - Refined: final list of test cases after applying critique feedback
        /// - Tokens: total tokens consumed by this API call (0 if all critiques are KEEP)
        /// Returns original test cases unchanged if API call fails after retries.
        /// </returns>
        /// <remarks>
        /// Short-circuits immediately if all critiques are KEEP — no API call is made.
        /// REVISE items have their PassNumber incremented to reflect the refinement pass number.
        /// </remarks>
        Task<(List<GeneratedTestCase> Refined, int Tokens)> RefineTestCasesAsync(
            List<GeneratedTestCase> testCases,
            List<CritiqueResult> critiques,
            string requirementsMarkdown);
    }
}
