namespace AITestAnalyzer.Models
{
    /// <summary>
    /// Represents a single test case generated by GEN Mode.
    /// Tracks which refinement pass produced it and when it was generated.
    /// </summary>
    public class GeneratedTestCase
    {
        /// <summary>Generated test case identifier (e.g. TC-GEN-001)</summary>
        public string TestId { get; set; } = "";

        /// <summary>Feature area this test case covers</summary>
        public string Feature { get; set; } = "";

        /// <summary>Test scenario description</summary>
        public string Scenario { get; set; } = "";

        /// <summary>Test priority: High, Medium, or Low</summary>
        public string Priority { get; set; } = "";

        /// <summary>Step-by-step test instructions</summary>
        public string Steps { get; set; } = "";

        /// <summary>Expected outcome after executing the steps</summary>
        public string ExpectedResult { get; set; } = "";

        /// <summary>
        /// Refinement pass that produced this test case.
        /// 1 = initial generation, 2 = first refinement, 3 = second refinement.
        /// </summary>
        public int PassNumber { get; set; } = 1;

        /// <summary>
        /// QA Mode score assigned after auto-scoring.
        /// Empty string if QA scoring has not been run yet.
        /// </summary>
        public string QAScore { get; set; } = "";

        /// <summary>UTC timestamp when this test case was generated</summary>
        public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
    }
}
